# ---
# apiVersion: v1 
# kind: configMap
# metadata:
#   name: app-secret-credentials
#   labels:
#     app: datakirk-backend
# data: 
#   POSTGRES_DB: devdb
#   POSTGRES_USER: devuser
#   POSTGRES_PASSWORD: changeme1234

