---
apiVersion: v1
kind: Service
metadata:
  name: redis-primary
  labels:
    app: redis
    role: primary
    tier: backend
spec:
  selector:
    app: redis
    role: primary
    tier: backend
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
